	nios_cpu u0 (
		.adi_stream_rx_clk_p       (<connected-to-adi_stream_rx_clk_p>),       //  adi_stream.rx_clk_p
		.adi_stream_frame_p        (<connected-to-adi_stream_frame_p>),        //            .frame_p
		.adi_stream_data_p         (<connected-to-adi_stream_data_p>),         //            .data_p
		.adi_stream_data_n         (<connected-to-adi_stream_data_n>),         //            .data_n
		.adi_stream_frame_n        (<connected-to-adi_stream_frame_n>),        //            .frame_n
		.adi_stream_rx_clk_n       (<connected-to-adi_stream_rx_clk_n>),       //            .rx_clk_n
		.adi_stream_tx_clk_p       (<connected-to-adi_stream_tx_clk_p>),       //            .tx_clk_p
		.adi_stream_tx_clk_n       (<connected-to-adi_stream_tx_clk_n>),       //            .tx_clk_n
		.clk_clk                   (<connected-to-clk_clk>),                   //         clk.clk
		.dac_MISO                  (<connected-to-dac_MISO>),                  //         dac.MISO
		.dac_MOSI                  (<connected-to-dac_MOSI>),                  //            .MOSI
		.dac_SCLK                  (<connected-to-dac_SCLK>),                  //            .SCLK
		.dac_SS_n                  (<connected-to-dac_SS_n>),                  //            .SS_n
		.gpio_in_port              (<connected-to-gpio_in_port>),              //        gpio.in_port
		.gpio_out_port             (<connected-to-gpio_out_port>),             //            .out_port
		.gpio_mini_export          (<connected-to-gpio_mini_export>),          //   gpio_mini.export
		.gpio_rf_in_port           (<connected-to-gpio_rf_in_port>),           //     gpio_rf.in_port
		.gpio_rf_out_port          (<connected-to-gpio_rf_out_port>),          //            .out_port
		.index_in_export           (<connected-to-index_in_export>),           //    index_in.export
		.index_out_index_frequency (<connected-to-index_out_index_frequency>), //   index_out.index_frequency
		.intern_gpio_export        (<connected-to-intern_gpio_export>),        // intern_gpio.export
		.oc_i2c_scl_pad_o          (<connected-to-oc_i2c_scl_pad_o>),          //      oc_i2c.scl_pad_o
		.oc_i2c_scl_padoen_o       (<connected-to-oc_i2c_scl_padoen_o>),       //            .scl_padoen_o
		.oc_i2c_sda_pad_i          (<connected-to-oc_i2c_sda_pad_i>),          //            .sda_pad_i
		.oc_i2c_sda_pad_o          (<connected-to-oc_i2c_sda_pad_o>),          //            .sda_pad_o
		.oc_i2c_sda_padoen_o       (<connected-to-oc_i2c_sda_padoen_o>),       //            .sda_padoen_o
		.oc_i2c_arst_i             (<connected-to-oc_i2c_arst_i>),             //            .arst_i
		.oc_i2c_scl_pad_i          (<connected-to-oc_i2c_scl_pad_i>),          //            .scl_pad_i
		.pll_MISO                  (<connected-to-pll_MISO>),                  //         pll.MISO
		.pll_MOSI                  (<connected-to-pll_MOSI>),                  //            .MOSI
		.pll_SCLK                  (<connected-to-pll_SCLK>),                  //            .SCLK
		.pll_SS_n                  (<connected-to-pll_SS_n>),                  //            .SS_n
		.reset_reset_n             (<connected-to-reset_reset_n>),             //       reset.reset_n
		.spi_ad9361_MISO           (<connected-to-spi_ad9361_MISO>),           //  spi_ad9361.MISO
		.spi_ad9361_MOSI           (<connected-to-spi_ad9361_MOSI>),           //            .MOSI
		.spi_ad9361_SCLK           (<connected-to-spi_ad9361_SCLK>),           //            .SCLK
		.spi_ad9361_SS_n           (<connected-to-spi_ad9361_SS_n>),           //            .SS_n
		.xb_gpios_export           (<connected-to-xb_gpios_export>)            //    xb_gpios.export
	);

