-- -------------------------------------------------------------
-- 
-- File Name: D:\Salukat\Development\Software\Quartus\BladeRF\hdl\fpga\ip\salukat\max_frequency\vhdl\max_frequency\max_frequency_tc.vhd
-- Created: 2020-12-29 17:32:45
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: max_frequency_tc
-- Source Path: max_frequency_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_32_0  : 32x slower than clk with last phase
-- enb_1_32_1  : 32x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY max_frequency_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_32_0                        :   OUT   std_logic;
        enb_1_32_1                        :   OUT   std_logic
        );
END max_frequency_tc;


ARCHITECTURE rtl OF max_frequency_tc IS

  -- Signals
  SIGNAL count32                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;

BEGIN
  Counter32 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count32 <= to_unsigned(1, 5);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count32 >= to_unsigned(31, 5) THEN
          count32 <= to_unsigned(0, 5);
        ELSE
          count32 <= count32 + to_unsigned(1, 5);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter32;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count32 = to_unsigned(31, 5) AND clk_enable = '1' ELSE '0';

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_1 <= '1';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  phase_1_tmp <= '1' WHEN count32 = to_unsigned(0, 5) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_32_0 <=  phase_0 AND clk_enable;

  enb_1_32_1 <=  phase_1 AND clk_enable;


END rtl;

