open_system('max_frequency_index');
open_system('gm_max_frequency_index');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 'user2');
annotate_port('max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 'user2');
annotate_port('max_frequency_index/max_index_frequency/FFT_streamer/FFT HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance1', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance2', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance2', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance3', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance3', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance4', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance4', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance5', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance5', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance6', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance6', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance7', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance7', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance8', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance8', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance9', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance9', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance10', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance10', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance11', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance11', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance12', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance12', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance13', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance13', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance14', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance14', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance15', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance15', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance16', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance16', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance17', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance17', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance18', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance18', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance19', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance19', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance20', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance20', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance21', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance21', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance22', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance22', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance23', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance23', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance24', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance24', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance25', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance25', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance26', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance26', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance27', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance27', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance28', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance28', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance29', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance29', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance30', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance30', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance31', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance31', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance32', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance32', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 'user2');
annotate_port('max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance1/Delay_ValidIn', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance1/Delay_ValidIn', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance1/DelayValidOut', 'user2');
annotate_port('gm_max_frequency_index/max_index_frequency/frequency_max/index_finder/for_each_instance1/DelayValidOut', 1, 1, 'Obstacle to clock-rate pipelining');
