-- -------------------------------------------------------------
-- 
-- File Name: D:\Salukat\Development\Software\Quartus\BladeRF\hdl\fpga\ip\salukat\max_frequency\vhdl\max_frequency_index\Maximum.vhd
-- Created: 2021-01-03 10:20:46
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Maximum
-- Source Path: Maximum/max_frequency_index/max_index_frequency/frequency_max/index_finder/Maximum
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.max_index_frequency_pkg.ALL;

ENTITY Maximum IS
  PORT( in0                               :   IN    vector_of_std_logic_vector13(0 TO 31);  -- sfix13 [32]
        out0                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END Maximum;


ARCHITECTURE rtl OF Maximum IS

  -- Signals
  SIGNAL in0_signed                       : vector_of_signed13(0 TO 31);  -- sfix13 [32]
  SIGNAL const_idx                        : vector_of_unsigned32(0 TO 31);  -- uint32 [32]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater : std_logic_vector(0 TO 15);  -- boolean [16]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val : vector_of_signed13(0 TO 15);  -- sfix13 [16]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx : vector_of_unsigned32(0 TO 15);  -- uint32 [16]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater : std_logic_vector(0 TO 7);  -- boolean [8]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val : vector_of_signed13(0 TO 7);  -- sfix13 [8]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx : vector_of_unsigned32(0 TO 7);  -- uint32 [8]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater : std_logic_vector(0 TO 3);  -- boolean [4]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val : vector_of_signed13(0 TO 3);  -- sfix13 [4]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx : vector_of_unsigned32(0 TO 3);  -- uint32 [4]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater : std_logic_vector(0 TO 1);  -- boolean [2]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_val : vector_of_signed13(0 TO 1);  -- sfix13 [2]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_idx : vector_of_unsigned32(0 TO 1);  -- uint32 [2]
  SIGNAL max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage5_idx : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  outputgen: FOR k IN 0 TO 31 GENERATE
    in0_signed(k) <= signed(in0(k));
  END GENERATE;

  const_idx(0) <= to_unsigned(0, 32);
  const_idx(1) <= to_unsigned(1, 32);
  const_idx(2) <= to_unsigned(2, 32);
  const_idx(3) <= to_unsigned(3, 32);
  const_idx(4) <= to_unsigned(4, 32);
  const_idx(5) <= to_unsigned(5, 32);
  const_idx(6) <= to_unsigned(6, 32);
  const_idx(7) <= to_unsigned(7, 32);
  const_idx(8) <= to_unsigned(8, 32);
  const_idx(9) <= to_unsigned(9, 32);
  const_idx(10) <= to_unsigned(10, 32);
  const_idx(11) <= to_unsigned(11, 32);
  const_idx(12) <= to_unsigned(12, 32);
  const_idx(13) <= to_unsigned(13, 32);
  const_idx(14) <= to_unsigned(14, 32);
  const_idx(15) <= to_unsigned(15, 32);
  const_idx(16) <= to_unsigned(16, 32);
  const_idx(17) <= to_unsigned(17, 32);
  const_idx(18) <= to_unsigned(18, 32);
  const_idx(19) <= to_unsigned(19, 32);
  const_idx(20) <= to_unsigned(20, 32);
  const_idx(21) <= to_unsigned(21, 32);
  const_idx(22) <= to_unsigned(22, 32);
  const_idx(23) <= to_unsigned(23, 32);
  const_idx(24) <= to_unsigned(24, 32);
  const_idx(25) <= to_unsigned(25, 32);
  const_idx(26) <= to_unsigned(26, 32);
  const_idx(27) <= to_unsigned(27, 32);
  const_idx(28) <= to_unsigned(28, 32);
  const_idx(29) <= to_unsigned(29, 32);
  const_idx(30) <= to_unsigned(30, 32);
  const_idx(31) <= to_unsigned(31, 32);

  ---- Tree max implementation ----
  ---- Tree max stage 1 ----
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(0) <= '1' WHEN in0_signed(0) >= in0_signed(1) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(0) <= in0_signed(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(0) = '1' ELSE
      in0_signed(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(0) <= const_idx(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(0) = '1' ELSE
      const_idx(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(1) <= '1' WHEN in0_signed(2) >= in0_signed(3) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(1) <= in0_signed(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(1) = '1' ELSE
      in0_signed(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(1) <= const_idx(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(1) = '1' ELSE
      const_idx(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(2) <= '1' WHEN in0_signed(4) >= in0_signed(5) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(2) <= in0_signed(4) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(2) = '1' ELSE
      in0_signed(5);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(2) <= const_idx(4) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(2) = '1' ELSE
      const_idx(5);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(3) <= '1' WHEN in0_signed(6) >= in0_signed(7) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(3) <= in0_signed(6) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(3) = '1' ELSE
      in0_signed(7);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(3) <= const_idx(6) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(3) = '1' ELSE
      const_idx(7);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(4) <= '1' WHEN in0_signed(8) >= in0_signed(9) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(4) <= in0_signed(8) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(4) = '1' ELSE
      in0_signed(9);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(4) <= const_idx(8) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(4) = '1' ELSE
      const_idx(9);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(5) <= '1' WHEN in0_signed(10) >= in0_signed(11) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(5) <= in0_signed(10) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(5) = '1' ELSE
      in0_signed(11);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(5) <= const_idx(10) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(5) = '1' ELSE
      const_idx(11);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(6) <= '1' WHEN in0_signed(12) >= in0_signed(13) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(6) <= in0_signed(12) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(6) = '1' ELSE
      in0_signed(13);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(6) <= const_idx(12) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(6) = '1' ELSE
      const_idx(13);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(7) <= '1' WHEN in0_signed(14) >= in0_signed(15) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(7) <= in0_signed(14) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(7) = '1' ELSE
      in0_signed(15);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(7) <= const_idx(14) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(7) = '1' ELSE
      const_idx(15);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(8) <= '1' WHEN in0_signed(16) >= in0_signed(17) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(8) <= in0_signed(16) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(8) = '1' ELSE
      in0_signed(17);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(8) <= const_idx(16) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(8) = '1' ELSE
      const_idx(17);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(9) <= '1' WHEN in0_signed(18) >= in0_signed(19) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(9) <= in0_signed(18) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(9) = '1' ELSE
      in0_signed(19);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(9) <= const_idx(18) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(9) = '1' ELSE
      const_idx(19);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(10) <= '1' WHEN in0_signed(20) >= in0_signed(21) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(10) <= in0_signed(20) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(10) = '1' ELSE
      in0_signed(21);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(10) <= const_idx(20) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(10) = '1' ELSE
      const_idx(21);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(11) <= '1' WHEN in0_signed(22) >= in0_signed(23) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(11) <= in0_signed(22) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(11) = '1' ELSE
      in0_signed(23);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(11) <= const_idx(22) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(11) = '1' ELSE
      const_idx(23);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(12) <= '1' WHEN in0_signed(24) >= in0_signed(25) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(12) <= in0_signed(24) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(12) = '1' ELSE
      in0_signed(25);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(12) <= const_idx(24) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(12) = '1' ELSE
      const_idx(25);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(13) <= '1' WHEN in0_signed(26) >= in0_signed(27) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(13) <= in0_signed(26) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(13) = '1' ELSE
      in0_signed(27);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(13) <= const_idx(26) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(13) = '1' ELSE
      const_idx(27);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(14) <= '1' WHEN in0_signed(28) >= in0_signed(29) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(14) <= in0_signed(28) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(14) = '1' ELSE
      in0_signed(29);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(14) <= const_idx(28) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(14) = '1' ELSE
      const_idx(29);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(15) <= '1' WHEN in0_signed(30) >= in0_signed(31) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(15) <= in0_signed(30) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(15) = '1' ELSE
      in0_signed(31);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(15) <= const_idx(30) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage1_isgreater(15) = '1' ELSE
      const_idx(31);

  ---- Tree max stage 2 ----
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(0) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(0) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(1) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(0) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(0) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(0) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(0) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(1) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(2) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(3) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(1) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(1) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(1) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(1) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(2) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(4) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(5) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(2) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(4) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(2) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(5);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(2) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(4) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(2) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(5);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(3) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(6) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(7) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(3) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(6) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(3) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(7);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(3) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(6) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(3) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(7);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(4) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(8) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(9) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(4) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(8) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(4) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(9);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(4) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(8) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(4) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(9);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(5) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(10) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(11) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(5) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(10) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(5) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(11);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(5) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(10) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(5) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(11);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(6) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(12) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(13) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(6) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(12) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(6) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(13);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(6) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(12) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(6) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(13);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(7) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(14) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(15) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(7) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(14) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(7) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_val(15);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(7) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(14) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage2_isgreater(7) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage1_idx(15);

  ---- Tree max stage 3 ----
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(0) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(0) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(1) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(0) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(0) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(0) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(0) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(1) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(2) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(3) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(1) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(1) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(1) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(1) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(2) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(4) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(5) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(2) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(4) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(2) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(5);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(2) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(4) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(2) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(5);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(3) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(6) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(7) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(3) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(6) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(3) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_val(7);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(3) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(6) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage3_isgreater(3) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage2_idx(7);

  ---- Tree max stage 4 ----
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater(0) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(0) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(1) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_val(0) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater(0) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_idx(0) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater(0) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(1);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater(1) <= '1' WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(2) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(3) ELSE
      '0';
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_val(1) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater(1) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_val(3);
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_idx(1) <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(2) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_treestage4_isgreater(1) = '1' ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage3_idx(3);

  ---- Tree max stage 5 ----
  
  max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage5_idx <= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_idx(0) WHEN max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_val(0) >= max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_val(1) ELSE
      max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage4_idx(1);

  out0 <= std_logic_vector(max_frequency_index_max_index_frequency_frequency_max_index_finder_Maximum_stage5_idx);

END rtl;

