
module i2c_si53304 (
	bladerf_oc_i2c_master_0_clock_sink_clk,
	bladerf_oc_i2c_master_0_reset_sink_reset,
	bladerf_oc_i2c_master_0_conduit_end_scl_pad_o,
	bladerf_oc_i2c_master_0_conduit_end_scl_padoen_o,
	bladerf_oc_i2c_master_0_conduit_end_sda_pad_i,
	bladerf_oc_i2c_master_0_conduit_end_sda_pad_o,
	bladerf_oc_i2c_master_0_conduit_end_sda_padoen_o,
	bladerf_oc_i2c_master_0_conduit_end_arst_i,
	bladerf_oc_i2c_master_0_conduit_end_scl_pad_i);	

	input		bladerf_oc_i2c_master_0_clock_sink_clk;
	input		bladerf_oc_i2c_master_0_reset_sink_reset;
	output		bladerf_oc_i2c_master_0_conduit_end_scl_pad_o;
	output		bladerf_oc_i2c_master_0_conduit_end_scl_padoen_o;
	input		bladerf_oc_i2c_master_0_conduit_end_sda_pad_i;
	output		bladerf_oc_i2c_master_0_conduit_end_sda_pad_o;
	output		bladerf_oc_i2c_master_0_conduit_end_sda_padoen_o;
	input		bladerf_oc_i2c_master_0_conduit_end_arst_i;
	input		bladerf_oc_i2c_master_0_conduit_end_scl_pad_i;
endmodule
