-- -------------------------------------------------------------
-- 
-- File Name: D:\Salukat\Development\Software\Quartus\BladeRF\hdl\fpga\ip\salukat\max_frequency\vhdl\max_frequency_reduced\FFT_streamer.vhd
-- Created: 2020-12-29 12:17:31
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FFT_streamer
-- Source Path: max_frequency_reduced/max_frequency/FFT_streamer
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.max_frequency_pkg.ALL;

ENTITY FFT_streamer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_16_0                        :   IN    std_logic;
        In1_re                            :   IN    vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
        In1_im                            :   IN    vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
        In2                               :   IN    std_logic;
        fft_data_re                       :   OUT   vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
        fft_data_im                       :   OUT   vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
        valid                             :   OUT   std_logic
        );
END FFT_streamer;


ARCHITECTURE rtl OF FFT_streamer IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT FFT_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
          dataIn_im                       :   IN    vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
          dataOut_im                      :   OUT   vector_of_std_logic_vector12(0 TO 15);  -- sfix12 [16]
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FFT_HDL_Optimized
    USE ENTITY work.FFT_HDL_Optimized(rtl);

  -- Signals
  SIGNAL FFT_HDL_Optimized_out1_re        : vector_of_std_logic_vector12(0 TO 15);  -- ufix12 [16]
  SIGNAL FFT_HDL_Optimized_out1_im        : vector_of_std_logic_vector12(0 TO 15);  -- ufix12 [16]
  SIGNAL FFT_HDL_Optimized_out2           : std_logic;

BEGIN
  u_FFT_HDL_Optimized : FFT_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => In1_re,  -- sfix12 [16]
              dataIn_im => In1_im,  -- sfix12 [16]
              validIn => In2,
              dataOut_re => FFT_HDL_Optimized_out1_re,  -- sfix12 [16]
              dataOut_im => FFT_HDL_Optimized_out1_im,  -- sfix12 [16]
              validOut => FFT_HDL_Optimized_out2
              );

  valid <= FFT_HDL_Optimized_out2;

  fft_data_re <= FFT_HDL_Optimized_out1_re;

  fft_data_im <= FFT_HDL_Optimized_out1_im;

END rtl;

